### ISSUE TITLE
Doesn't work because this plugin requires its own NPM installation within Nuget

### ISSUE THREAD

**Issue by Montago** [BamButz/msbuild-tailwindcss#10]
The build process fails because the plugin is looking for NPM / Modues in the wrong directory ... 

NPM together with Tailwind is installed in relation to the SLN file .. maybe this plugin should look for that ? 

Rebuild started...
1>------ Rebuild All started: Project: ParkWebApp.Shared, Configuration: Debug Any CPU ------
1>  ParkWebApp.Shared -> C:\develop\Parkerings-MobilWebApp\ParkWebApp.Shared\bin\Debug\ParkWebApp.Shared.dll
2>------ Rebuild All started: Project: ParkWebApp, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: ParkWebApp.Api, Configuration: Debug Any CPU ------
2>  CompileTailwindCSS: Cleaning 
2>  CompileTailwindCSS: Cleaning C:\develop\Parkerings-MobilWebApp\packages\BamButz.MSBuild.TailwindCSS.1.3.0\build\../pa
2>  ckage-lock.json
2>  CompileTailwindCSS: Cleaning C:\develop\Parkerings-MobilWebApp\packages\BamButz.MSBuild.TailwindCSS.1.3.0\build\../ta
2>  ilwind.config.js
2>  ParkWebApp -> C:\develop\Parkerings-MobilWebApp\ParkWebApp\bin\ParkWebApp.dll
2>  internal/modules/cjs/loader.js:883
2>    throw err;
2>    ^
2>  
2>EXEC : error : Cannot find module 'C:\develop\Parkerings-MobilWebApp\packages\BamButz.MSBuild.TailwindCSS.1.3.0\node_mo
2>dules\npm\bin\npm-cli.js'
2>      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
2>      at Function.Module._load (internal/modules/cjs/loader.js:725:27)
2>      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
2>      at internal/main/run_main_module.js:17:47 {
2>    code: 'MODULE_NOT_FOUND',
2>    requireStack: []
2>  }
2>  internal/modules/cjs/loader.js:883
2>    throw err;
2>    ^
2>  
2>EXEC : error : Cannot find module 'C:\develop\Parkerings-MobilWebApp\packages\BamButz.MSBuild.TailwindCSS.1.3.0\node_mo
2>dules\npm\bin\npm-cli.js'
2>      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
2>      at Function.Module._load (internal/modules/cjs/loader.js:725:27)
2>      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
2>      at internal/main/run_main_module.js:17:47 {
2>    code: 'MODULE_NOT_FOUND',
2>    requireStack: []
2>  }
2>C:\develop\Parkerings-MobilWebApp\packages\BamButz.MSBuild.TailwindCSS.1.3.0\build\BamButz.MSBuild.TailwindCSS.targets(
2>31,9): error MSB3073: The command ""npm" install" exited with code 1.
3>  ParkWebApp.Api -> C:\develop\Parkerings-MobilWebApp\ParkWebApp.Api\bin\ParkWebApp.Api.dll

**Comment by BamButz** [comment]
> The build process fails because the plugin is looking for NPM / Modues in the wrong directory ...
This is the intended way, so that is not the problem.

Do you use a tailwind config? If so, could you provide it, so I can investigate the issue?

**Comment by Montago** [comment]
I'm in the middle of setting up a new solution with MVC + TailWind .. so everything is a pretty blank slate.. 
My config is the default created.

**Comment by Montago** [comment]
update - found out that i was running the npm command in the package manager terminal which doesn't do well with NPM .. 
after switching to powershell it runs like it should  

- so, not the issue.

**Comment by BamButz** [comment]
IDK, if NPM is not running in general on the package manager terminal, I'm afraid we can't do anything to support it.
I will install VS in the near future and try to get some insights into this issue.
