### ISSUE TITLE
no npm-cli.js in relation path

### ISSUE THREAD

**Issue by rc1021** [BamButz/msbuild-tailwindcss#11]
I got the error message when I compiler project

```
Cannot find module 'D:\Projects\Demo1\packages\BamButz.MSBuild.TailwindCSS.1.3.0\node_modules\npm\bin\npm-cli.js'	
Cowell.eWebNet.Apps.eWebFront	D:\Projects\Demo1\EXEC
```

**Comment by BamButz** [comment]
Could you try to install NPM globally? 
```
npm i npm@latest -g
```

**Comment by rc1021** [comment]
but new issue 

![1631009557238](https://user-images.githubusercontent.com/1082597/132328192-c1fa689e-791f-409c-84ec-5a4279e96e6e.jpg)

Extra double quotes in line: 31, 51 in BamButz.MSBuild.TailwindCSS.targets

`&quot;$(NodeCli)&quot;` -> `$(NodeCli)`

**Comment by rc1021** [comment]
> but new issue
> 
> ![1631009557238](https://user-images.githubusercontent.com/1082597/132328192-c1fa689e-791f-409c-84ec-5a4279e96e6e.jpg)
> 
> Extra double quotes in line: 31, 51 in BamButz.MSBuild.TailwindCSS.targets
> 
> `&quot;$(NodeCli)&quot;` -> `$(NodeCli)`

I have determined that are the same problem with #10

**Comment by rr222cy** [comment]
Great work on this NuGet, eager to try it out.
Hitting the same error as @rc1021 though using Visual Studio 2022, C# .NET 6.

Navigating to the NuGet installation path for your package and running "npm install" works, but the build then halts on the next command needed to build the CSS and so on. From what I can see and as @rc1021 stated above it seems related to the commands having double quotation marks, perhaps?

**Comment by BamButz** [comment]
I'm not really sure about the double quotes, to me, they are correct.
I will check this behavior later in the day.
