### ISSUE TITLE
Dev Experience

### ISSUE THREAD

**Issue by menasheh** [BamButz/msbuild-tailwindcss#12]
I get that this would automate the npm part of the build during .NET build process, but how would you deal with incremental builds during development?

**Comment by techopswhiz** [comment]
What I meant to ask about was support for [just in time mode](https://tailwindcss.com/docs/just-in-time-mode).

This makes the CSS file optimized depending on which css classes are actually used in your html. 

What I want to know is if there is a workflow that would allow this to work while making changes to the cshtml files, etc.

Without just in time mode, there is one build that happens and that's it. With just in time mode, there are file watchers on the configured files and the tailwind rebuilds to include any added classes on the fly.

Does that make sense?

**Comment by BamButz** [comment]
You could try out whether setting the configuration entries is sufficient.
If not, we don't currently have any explicit support, but I would put it on the list.
