### ISSUE TITLE
Config not being used on Windows

### ISSUE THREAD

**Issue by Epictek** [BamButz/msbuild-tailwindcss#4]
I have a config.js in the root of the project but it doesn't seem to be apply my config but building the css file works fine. 

It works when I build the same project on Linux (Rider and dotnet cli) but doesn't work on Windows (Visual Studio and dotnet cli). My colleague also has the same issue on his machine.

Some home debugging this would be appreciated :smile:

**Comment by BamButz** [comment]
It would be nice if you could provide some sample project so that I can reproduce your case.

**Comment by Epictek** [comment]
Apologies for the delay, here you go :) 

https://github.com/Epictek/tailwindtest

**Comment by BamButz** [comment]
Yep, I spotted the bug.
I'm rolling out the new version tomorrow.

Thank you for reporting the bug and for providing the sample project.
